#!/usr/bin/env python3
from src.language import TXT
from src.prompt import Prompt
from src.seedship import Seedship
from src.util import clear_screen, get_screen_size


TXT.prompt_available_languages()

clear_screen()
rows, cols = get_screen_size()
input(rows // 2 * '\n' + TXT['messages']['start_game'].center(cols))

clear_screen()
s = Seedship()
s.find_new_planet()
Prompt.serve_forever(s)
