#!/usr/bin/env python3
from src.language import TXT
from src.prompt import Prompt
from src.seedship import Seedship
from src.util import clear_screen, get_screen_size


LANGUAGE = 'en-US'
TXT.set_language(LANGUAGE)

clear_screen()
rows, cols = get_screen_size()
input(rows // 2 * '\n' + '[ENTER PARA COMEÇAR A JORNADA]')
clear_screen()
s = Seedship()
s.find_new_planet()
Prompt.serve_forever(s)
